name: Build Task App APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17 con Caché de Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # ⚡ Guarda en caché las librerías para ejecuciones futuras

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Dar permisos de ejecución a Gradle Wrapper
        run: chmod +x gradlew

      - name: Compilar APK Debug
        run: ./gradlew assembleDebug --no-daemon

      - name: Subir Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: taskapp-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
